# puber -- build / run / test.
#
# `build`, `run` and `test` are the three entry points. Nothing else should be needed.
SHELL := /bin/bash
.DEFAULT_GOAL := help

# Safety net: if a recipe fails, delete the file it was writing, so make retries instead
# of treating the half-written file as done.
.DELETE_ON_ERROR:

# AC18 case 1: containers run as the host user and no root.
export HOST_UID := $(shell id -u)
export HOST_GID := $(shell id -g)

# Running make itself as root defeats the above: HOST_UID/HOST_GID become 0:0; this refuses before the fact.
ifeq ($(HOST_UID),0)
$(error refusing to run as root: containers would run as root and write root-owned files into the working tree (AC18). Run make as a normal user)
endif

COMPOSE_FILE := infra/docker-compose.yml
COMPOSE      := docker compose -f $(COMPOSE_FILE)
DB_PASSWORD_FILE     := infra/.env
GRADLE_HOME  := .gradle-home

# Why do we need this?
# `clean` deletes infra/.env, and compose refuses to read its file without that variable.
# So without a placeholder here, running `clean` a second time fails on its own first line.
# The value is never used: teardown authenticates against nothing.
COMPOSE_DOWN := MATCHING_SERVICE_DB_PASSWORD=unused-for-teardown $(COMPOSE)

# A new service directory is picked up with no edit here. Keyed on the wrapper, so a stray
# file cannot become a phantom service.
SERVICES         := $(notdir $(patsubst %/,%,$(sort $(dir $(wildcard services/*/gradlew)))))
ANALYZER_SOURCES := $(wildcard static-analyzers/*.gradle)

# What to analyse. `.` is the working tree; pre-commit overrides it with a copy of the
# index, so the commit gate checks what is actually being committed.
TREE ?= .

# All Gradle runs go through the profile-gated `tests` container, which holds the network,
# mount, environment and UID/GID. --no-deps where no datastore is needed.
GRADLE       := $(COMPOSE) run --rm --no-deps -T
GRADLE_STACK := $(COMPOSE) run --rm -T

.PHONY: help build run stop test test-unit test-integration static-analysis format hooks \
        analyzer-config images clean verify-no-root-owned-files gradle-home

help:
	@echo
	@echo "  make build            Build the project: every service, each via its own Gradle wrapper"
	@echo "  make run              Run the project: bring the Compose stack up"
	@echo "  make test             Run all tests -- unit and integration"
	@echo
	@echo "  make stop             Bring the stack down"
	@echo "  make format           Reformat every service's sources (fixes what pre-commit rejects)"
	@echo "  make static-analysis SERVICE=<name>   One service's static analysis (what pre-commit invokes)"
	@echo "  make test-unit        Unit tests only"
	@echo "  make test-integration Integration tests only, against the real stack"
	@echo "  make clean            Down the stack with its volumes, remove build output and the local env file"
	@echo
	@echo "  services discovered:  $(SERVICES)"

# One random password for the local Postgres. Written to a temp file and moved into place,
# so a failed run leaves nothing half-written for make to treat as done.
$(DB_PASSWORD_FILE):
	@mkdir -p $(dir $@)
	@umask 077 && { \
	  echo "# Generated by make. Gitignored, never committed."; \
	  echo "# Postgres only reads this password when it first creates its volume, and ignores it"; \
	  echo "# afterwards. Deleting this file while a volume exists locks you out of that volume:"; \
	  echo "# the password cannot be recovered. \`make clean\` drops volumes and keeps this file."; \
	  echo "# To rotate, delete this file AND every volume initialised from it, together."; \
	  echo "MATCHING_SERVICE_DB_PASSWORD=$$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)"; \
	} > $@.tmp
	@test -s $@.tmp
	@grep -q '^MATCHING_SERVICE_DB_PASSWORD=.\{32\}$$' $@.tmp
	@mv $@.tmp $@
	@echo "==> generated $@"

# Copies the Gradle cache baked into the build image into the workspace. Without it a fresh
# clone re-downloads Gradle and every dependency.
gradle-home: $(GRADLE_HOME)

# Temp dir then move, so $@ never exists half-seeded -- make would treat that as done
# forever. `.DELETE_ON_ERROR:` cannot help here: it does not delete directories.
$(GRADLE_HOME):
	@rm -rf $@.tmp
	@mkdir -p $@.tmp
	@echo "==> seeding $@ from the build image's baked Gradle cache"
	@$(GRADLE) --entrypoint sh tests -c \
	  'cp -a /home/app/.gradle/caches /home/app/.gradle/wrapper /workspace/$(GRADLE_HOME).tmp/'
	@mv $@.tmp $@

# AD-52: the single analyzer config, copied into each service's build output before its
# wrapper runs. Not a Gradle `Copy` task: `apply from:` resolves before a `Copy` would run.
# Also clears build/spotless-clean. Spotless keeps its own copy of every source file there
# to work out what changed; rename or move a file and that copy no longer resolves, so the
# task dies with "unable to determine incremental changes" instead of formatting. Spotless
# needs the tracking, so it cannot be switched off -- the copies have to go instead. Every
# target that invokes Gradle depends on this one, so the failure cannot come back.
analyzer-config:
	@test -n "$(ANALYZER_SOURCES)" || { \
	  echo "no analyzer configuration found in static-analyzers/*.gradle -- AD-52 requires exactly one versioned source" >&2; \
	  exit 1; \
	}
	@for svc in $(SERVICES); do \
	  mkdir -p $(TREE)/services/$$svc/build/static-analyzers || exit 1; \
	  cp $(ANALYZER_SOURCES) $(TREE)/services/$$svc/build/static-analyzers/ || exit 1; \
	  rm -rf $(TREE)/services/$$svc/build/spotless-clean || exit 1; \
	done

# AC11: a fresh clone plus a build restores both gates. core.hooksPath points at the
# tracked scripts, so nothing is copied into the untracked .git/hooks.
hooks:
	@git rev-parse --git-dir >/dev/null 2>&1 || { \
	  echo "==> not a git checkout -- skipping hook installation"; exit 0; }
	@git config core.hooksPath .githooks
	@chmod +x .githooks/pre-commit .githooks/pre-push
	@echo "==> git hooks installed (core.hooksPath=.githooks)"

images: $(DB_PASSWORD_FILE) analyzer-config
	$(COMPOSE) --profile tools build

# Analysis and tests run before the image is tagged. Otherwise a failed build leaves a
# tagged image behind, and `make run` would serve it (AC16).
build: hooks $(DB_PASSWORD_FILE) gradle-home analyzer-config
	@for svc in $(SERVICES); do \
	  echo "==> build $$svc"; \
	  $(GRADLE) --workdir /workspace/services/$$svc tests ./gradlew build --console=plain || exit 1; \
	done
	$(COMPOSE) --profile tools build
	@$(MAKE) --no-print-directory verify-no-root-owned-files

run: $(DB_PASSWORD_FILE) images
	$(COMPOSE) up -d --wait matching-postgres matching-service
	@echo "==> stack up."

stop:
	$(COMPOSE_DOWN) down

# AC18's standing check. The failure it catches is otherwise silent until someone
# tries to delete a build directory and cannot.
verify-no-root-owned-files:
	@offender=$$(find . -user root -print -quit 2>/dev/null); \
	if [ -n "$$offender" ]; then \
	  echo "" >&2; \
	  echo "root-owned file in the working tree: $$offender" >&2; \
	  echo "A container that mounts this repository ran as root, which AC18 forbids." >&2; \
	  echo "Check HOST_UID/HOST_GID are exported and that make was not run under sudo." >&2; \
	  exit 1; \
	fi
	@echo "==> no root-owned files in the working tree (AC18)"

# What the pre-commit hook invokes, for one service: static analysis and nothing else.
# TREE lets the hook point this at a materialised copy of the index.
static-analysis: $(DB_PASSWORD_FILE) gradle-home analyzer-config
	@test -n "$(SERVICE)" || { echo "usage: make static-analysis SERVICE=<name>" >&2; exit 2; }
	@test -d "$(TREE)/services/$(SERVICE)" || { echo "no such service: $(TREE)/services/$(SERVICE)" >&2; exit 2; }
	$(GRADLE) --workdir /workspace/$(TREE)/services/$(SERVICE) tests ./gradlew staticAnalysis --console=plain

# Fixes what `static-analysis` rejects. Always the working tree, never $(TREE). Remember to
# `git add` the result: the commit gate reads the index.
format: $(DB_PASSWORD_FILE) gradle-home analyzer-config
	@for svc in $(SERVICES); do \
	  echo "==> format $$svc"; \
	  $(GRADLE) --workdir /workspace/services/$$svc tests ./gradlew spotlessApply --console=plain || exit 1; \
	done

test-unit: $(DB_PASSWORD_FILE) gradle-home analyzer-config
	@for svc in $(SERVICES); do \
	  echo "==> unit tests: $$svc"; \
	  $(GRADLE) --workdir /workspace/services/$$svc tests ./gradlew test --console=plain || exit 1; \
	done

# Brings up what it needs, so this works on a fresh clone. Waits on the healthcheck,
# never on a sleep.
test-integration: $(DB_PASSWORD_FILE) gradle-home analyzer-config
	$(COMPOSE) up -d --wait matching-postgres
	@for svc in $(SERVICES); do \
	  echo "==> integration tests: $$svc"; \
	  $(GRADLE_STACK) --workdir /workspace/services/$$svc tests ./gradlew integrationTest --console=plain || exit 1; \
	done

# Exactly test-unit + test-integration. The split exists because the hooks need it
# (pre-commit = static analysis, pre-push = everything) and must not drift from this.
test: test-unit test-integration

# Deliberately does NOT delete $(DB_PASSWORD_FILE). Dropping the volume alone is safe --
# the next run re-creates it from the same password. Dropping the file alone is not: the
# password inside an existing volume cannot be recovered, and Postgres ignores
# POSTGRES_PASSWORD after the first start.
#
# That asymmetry matters because this repository is worked on from more than one Docker
# daemon (a laptop and a container that mounts the same tree). `down -v` reaches only the
# daemon it runs on, while the file is shared -- so deleting both here wiped one machine's
# volume and the other machine's password. Keeping the file makes every daemon initialise
# its own volume from the same credentials.
#
# To rotate the password, delete the file by hand and drop the volume on every daemon that
# has one.
clean:
	$(COMPOSE_DOWN) --profile tools down -v --remove-orphans
	rm -rf services/*/build services/*/.gradle $(GRADLE_HOME) $(GRADLE_HOME).tmp .pre-commit-tree
